# yaml
# ---------------------------------------------------------------------------
# Logging configuration
# ---------------------------------------------------------------------------
logging:
  level: "INFO"
  logdir: "logs"
  retentions_day: 14

# ---------------------------------------------------------------------------
# Domains configuration
# ---------------------------------------------------------------------------
domains:
  taz:
    mongodb_collection_name: "taz"
    class_path: "lib.domain.taz:TAZ"
    base_urls:
      - "https://taz.de/"

# ---------------------------------------------------------------------------
# MongoDB configuration
# ---------------------------------------------------------------------------
mongodb:
  database_name: "german_news_papaer"
