# yaml
# ---------------------------------------------------------------------------
# Logging configuration
# ---------------------------------------------------------------------------
logging:
  level: "INFO"
  logdir: "logs"
  retentions_day: 14

# ---------------------------------------------------------------------------
# Domains configuration
# ---------------------------------------------------------------------------
domains:
  - name: taz
    collection: "taz"
    class_path: "lib.domain.taz:TAZ"
    base_url: "https://taz.de/"

# ---------------------------------------------------------------------------
# MongoDB configuration
# ---------------------------------------------------------------------------
mongodb:
  uri: "mongodb://localhost:27017"    # replace with credentials/host if required
  database_name: "german_news_paper"

# ---------------------------------------------------------------------------
# Scheduler configuration
# ---------------------------------------------------------------------------
scheduler:
  enabled: true
  time: "01:00"
  timezone: "Europe/Berlin"

